{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.svistunovdv",
    "module": "logging-starter",
    "version": "1.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.5-SNAPSHOT.jar",
          "url": "logging-starter-1.5-SNAPSHOT.jar",
          "size": 9266,
          "sha512": "b053a3652c562d3b474714ce5cf7f1d188f109b5fe253ecd651e5dd3f8b7638f1d1b98363f503f9a077cf3e3254ca8a2c39ebb968cf04fd62a346f9eacb4c7d4",
          "sha256": "5a14e9a7c804c516d2b1f7e67a08a596afbc0b8e3b687537477bff20b2344421",
          "sha1": "bfbca3c10072a8d0d430df26c4e8d131835203e2",
          "md5": "e401014f9a0ef971918a7f00f6f72147"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.5-SNAPSHOT.jar",
          "url": "logging-starter-1.5-SNAPSHOT.jar",
          "size": 9266,
          "sha512": "b053a3652c562d3b474714ce5cf7f1d188f109b5fe253ecd651e5dd3f8b7638f1d1b98363f503f9a077cf3e3254ca8a2c39ebb968cf04fd62a346f9eacb4c7d4",
          "sha256": "5a14e9a7c804c516d2b1f7e67a08a596afbc0b8e3b687537477bff20b2344421",
          "sha1": "bfbca3c10072a8d0d430df26c4e8d131835203e2",
          "md5": "e401014f9a0ef971918a7f00f6f72147"
        }
      ]
    }
  ]
}
