{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.svistunovdv",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 1345,
          "sha512": "1bdfccb0037dd4325b739e79c86acb34cedce69ff7f7ca687bc6ee4fbecfbf9b4cda88bec4ae4304ed8f3109ef1f711d5aebfcd379721ce89656598318979f69",
          "sha256": "c891bab5f0c7334e6100ac435d11ebda2a5177800c5f664320680edc9bc8ddb0",
          "sha1": "523d6c75afe676e047270887ede59376689abc45",
          "md5": "000b8aaf38df85eede2f3a99db1e5f06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 1345,
          "sha512": "1bdfccb0037dd4325b739e79c86acb34cedce69ff7f7ca687bc6ee4fbecfbf9b4cda88bec4ae4304ed8f3109ef1f711d5aebfcd379721ce89656598318979f69",
          "sha256": "c891bab5f0c7334e6100ac435d11ebda2a5177800c5f664320680edc9bc8ddb0",
          "sha1": "523d6c75afe676e047270887ede59376689abc45",
          "md5": "000b8aaf38df85eede2f3a99db1e5f06"
        }
      ]
    }
  ]
}
