{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.svistunovdv",
    "module": "logging-starter",
    "version": "1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.4-SNAPSHOT.jar",
          "url": "logging-starter-1.4-SNAPSHOT.jar",
          "size": 1347,
          "sha512": "76bae8d18fcd77be694c1ec4d35a4315e870e6b61e8b7c78c789272814a72084d26394f565ca3551ad953f4c3fcd35cde73799c4b1334a88ac27a5fc3022fc04",
          "sha256": "122516ada7d701b05cca50fed35fa16e6003ae71c8c7dea9fdfd5592f2e2ade3",
          "sha1": "5462b3e32fb377b8405c8fbd823f5f5f007550b7",
          "md5": "72b895b0100cbcd8d3eeca6305a17b9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.4-SNAPSHOT.jar",
          "url": "logging-starter-1.4-SNAPSHOT.jar",
          "size": 1347,
          "sha512": "76bae8d18fcd77be694c1ec4d35a4315e870e6b61e8b7c78c789272814a72084d26394f565ca3551ad953f4c3fcd35cde73799c4b1334a88ac27a5fc3022fc04",
          "sha256": "122516ada7d701b05cca50fed35fa16e6003ae71c8c7dea9fdfd5592f2e2ade3",
          "sha1": "5462b3e32fb377b8405c8fbd823f5f5f007550b7",
          "md5": "72b895b0100cbcd8d3eeca6305a17b9a"
        }
      ]
    }
  ]
}
